( This gcode generated by /Applications/EAGLE-6.1.0/ulp/pcb-gcode.ulp )
( Copyright 2005 by John Johnson. See readme.txt for licensing terms. )

( This file generated from the board /Users/lpatiny/git/legoino/eagle/modules/I2C/LCD-MCP23008/lcd-i2c.brd )
( This file generated 1/10/13 08:35  )

G21

G90
G00 Z12.7000 
G00 X0 Y0
M03
G04 P3.000000
G01 X0.0000 Y43.1800 
G01 X-52.0700 Y43.1800 
G01 X-52.0700 Y0.0000 
G01 X0.0000 Y0.0000 
(File Footer)
G00 Z12.7000 
M05
M02
